---
title: "Sample code: Read 2007 diagnosis data with for loop"
author: "Bing-Jie Yen"
date: "May 16th, 2022"
output: html_document
---



```{r load packages and map file names }
Sys.setenv(TZ='America/Fort_Wayne')
#------------------------------------------------
# If the read_parquet keeps crashing while running, install arrow under the working directory, it is slate here
#------------------------------------------------
myPaths <- .libPaths()
myPaths <- c(myPaths, '/N/slate/yenb/R/x86_64-pc-linux-gnu-library/4.0')
.libPaths(myPaths)
# Example code for reading optum parquet files

# In the terminal execute the following before starting R or Rstudio;
# this loads the parquet C++ libraries so R can see them. 

# module load arrow

# Install and load packages.

if (!require("pacman")) {
  install.packages("pacman")
  library(pacman)
}

p_load(tictoc, data.table, ggplot2, janitor, touch, stringr, fs, dplyr,lubridate,expss)


library(arrow) # if this is not working, remove.packages("arrow") in rstudio. Close the r studio and go to terminal: (1)module load rstudio (2) module load arrow (3) rstudio &

# Set threads for data.table at a lower number to make sure we don't use too
# many resources on RED
setDTthreads(10)

# Map the optum table name to the the corresponding part of the file name
# This has nothing to do with running this script, and is just for 
# convenience so one doesn't have to look this up.

file_patterns <- c("mbrwdeath", "ses", "mbr_co_enroll", "mbr_enroll",
                  "m", "diag", "proc", "c", "r", "lr", "provider", 
                  "provider_bridge", "lu_diagnosis", "lu_ndc",
                  "lu_procedure")

# The names(file_patterns) are the detailed name for file_patterns

names(file_patterns) <- c("DOD", "SES", "MEMBER_CONTINUOUS_ENROLLMENT",
                          "MEMBER_ENROLLMENT", "MEDICAL", "MED_DIAGNOSIS", 
                          "MED_PROCEDURE", "CONFINEMENT", "RX",
                          "LABRESULT", "PROVIDER", "PROVIDER_BRIDGE",
                          "LU_DIAGNOSIS", "LU_NDC", "LU_PROCEDURE")

print(file_patterns['RX']) 


# Use ses data
optum_data_dir = path_abs('/N/project/optum/data/parquet/ses_81_202107') # let's use sample data (2% of raw) instead of parquet data because it takes too much memoery after 

# Convenience function for getting the full path to parquet files
# You don't need to use this if you prefer some other way of getting
# the full paths to the files.

get_filepaths <- function (re_pattern) {
    dir_info(optum_data_dir) %>% 
    filter(str_detect(path, re_pattern)) %>%
    select(path)
}
```

```{r read the eligible ID list}
# load ID_list from 00.3_full_enroll.rmd
# The PATID in this list include patients who (1) adult patients from 18 to 64 years old (2) continuous enroll at least 365*2 days (3) Unique race code (4) known sex identity
ID_list<-fread("/N/slate/yenb/R/Optum/full_data/ID_list_ses_mbrcoenroll.csv")
ID_list$PATID<-as.factor(ID_list$PATID)
```

# Read MH diagnosis files for 2007-2015
## Generate  diagnosis list for ICD-9

```{r generate psychotic diagnosis list}
library(touch)
print(file_patterns['MED_DIAGNOSIS'])
diagnosis_file_list<-list.files(path=optum_data_dir, "ses_diag")
diagnosis_file_list 

# Set up location for saving diagnosis files
diagnosis_path<-"/N/slate/yenb/R/Optum/full_data/diagnosis_crosstable/"

# Generate MH diagnosis
length<-1000 # because there are at most 3 digits after F2
## (1) Psychotic disorders: ICD-10 include F20-F29, According to     https://www.icd10data.com/Convert/Results, ICD -9 include the following accordingly: 
psychotic_list<-rep("F2",length)
psychotic_num<-seq(0,999,length=1000) # because there are at most 3 digits after F2
psychotic_num<-str_pad(psychotic_num, 3, pad = "0")
psychotic_disorder<-paste(psychotic_list,psychotic_num,sep="")
psychotic_disorder

psychotic_list_1<-unique(icd_map(substr(psychotic_disorder,1,3),from=10,to=9))
psychotic_list_1<-unlist(strsplit(psychotic_list_1,","))
psychotic_list_1
psychotic_list_2<-unique(icd_map(substr(psychotic_disorder,1,4),from=10,to=9))
psychotic_list_2<-unlist(strsplit(psychotic_list_2,","))
psychotic_list_2

psychotic_list_3<-unique(icd_map(substr(psychotic_disorder,1,5),from=10,to=9))
psychotic_list_3<-unlist(strsplit(psychotic_list_3,","))
psychotic_list_3
psychotic_list<-unique(append(psychotic_list_1,psychotic_list_2))
psychotic_list<-unique(append(psychotic_list,psychotic_list_3))
psychotic_list<-unlist(strsplit(psychotic_list,c("[+]")))
psychotic_list # "30122" "2970"  "2971"  "2972"  "2983"  "2984"  "2988"  "2973"  "2989"  "29530" "29510" "29520" "29590" "29560" "29570", "29540" "29580"

attr(psychotic_list,"doc")<-"psychotic_list: psychotic disorders converts from ICD10,F20-F29, to ICD 9"
save(psychotic_list,file="/N/slate/yenb/R/Optum/full_data/diagnosis_crosstable/ICD9_psychotic_list.RData")
psychotic_list<-data.table(psychotic_list)
fwrite(psychotic_list,paste(diagnosis_path,"ICD9_psychotic_list.csv",sep=""))

```


## Read and merge 2007 q1 to 2007 q4 diagnosis data

```{r round 1 to 4}
library(touch)
print(file_patterns['MED_DIAGNOSIS'])
diagnosis_file_list<-list.files(path=optum_data_dir, "ses_diag")
diagnosis_file_list

tic("running")
print("start to run")
# include 2007q1 to 2007 q4
diagnosis_data_1_4<-data.frame()
for (i in 1:4){
  file_path = get_filepaths(diagnosis_file_list[i])$path 
  # Read the parquet file with just the desired columns.
  
  data <- arrow::read_parquet(file_path, select =c("PATID","CLMID","DIAG","ICD_FLAG","LOC_CD","FST_DT"))
  data$PATID<-as.factor(data$PATID)
  # Extract eligible population
  data<-data%>%filter(PATID %in% ID_list$PATID)
  # add year and quarter number variables
  file_name<-strsplit(file_path,"\\/|\\.")[[1]][8]
  data$year<-paste(strsplit(file_name,split="")[[1]][9:12],collapse="")# extract the year
  data$quarter<-strsplit(file_name,split="")[[1]][14]# extract quarter
  
  
  setDT(data)
  # Mental health disorders: ICD-9 290-319, suicide attempt E950-E959
  data$MH_diagnosis<-ifelse(substr(data$DIAG,1,3) %in% seq(290,319),1,0)
  
  table(data$DIAG)
  
  # Generate psychotic diagnosis
  data$psychotic_disorder<-ifelse(data$DIAG %in% psychotic_list,1,0)
  
  
  # Delete the observations which are not related to mental health disorders
  data<-data%>%filter(MH_diagnosis==1|psychotic_disorder==1)
  
  #
  diagnosis_data_1_4<-rbind(diagnosis_data_1_4,data)
  gc()
}

print("almost finish running")
toc()
fwrite(diagnosis_data_1_4,pate(diagnosis_path,"full_data/ses_diag_1_5.csv",sep=""))

#  SECONDS
```











